---
- name: Add Seafile repository
  ansible.builtin.deb822_repository:
    name: seafile
    types: deb
    uris: https://linux-clients.seafile.com/seafile-deb/{{ ansible_local['ubuntu_distro_info']['lts']['codename'] }}/
    suites: stable
    components: main
    architectures: amd64
    signed_by: https://linux-clients.seafile.com/seafile.asc

- name: Install libwebsockets16 from Ubuntu Jammy archive
  ansible.builtin.apt:
    deb: http://archive.ubuntu.com/ubuntu/pool/universe/libw/libwebsockets/libwebsockets16_4.0.20-2ubuntu1_amd64.deb

- name: Install Seafile Client
  ansible.builtin.apt:
    name: seafile-gui
    update_cache: true
    state: latest
...
