---
- name: Add Spotify repository
  ansible.builtin.deb822_repository:
    name: spotify
    types: deb
    uris: http://repository.spotify.com
    suites: stable
    components: non-free
    architectures: amd64
    signed_by: https://download.spotify.com/debian/pubkey_6224F9941A8AA6D1.gpg

- name: Install spotify
  ansible.builtin.apt:
    name: spotify-client
    update_cache: yes
    state: latest
...
